### ISSUE TITLE
glcontext dependency not captured

### ISSUE THREAD

**Issue by farleylai** [conda-forge/moderngl-feedstock#11]
`modengl` relies on a separate package `glcontext` to create the context which seems only available on pypi.
Is it possible to distribute `glcontext` on the anaconda repo?

```py
>>> import moderngl
>>> ctx = moderngl.create_context(standalone=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/farleylai/miniconda3/envs/sinet37/lib/python3.7/site-packages/moderngl/context.py", line 1454, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
ModuleNotFoundError: No module named 'glcontext'
```

**Comment by nexplor** [comment]
This is critical, as moderngl is pretty much unusable without glcontext.

**Comment by patricksnape** [comment]
This has been fixed now :)
